language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

matrix:
  allow_failures:
    - python: "pypy"

install:
  - pip install -r test-requirements.txt --use-mirrors
  - python setup.py install

script: make test